; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:Arm]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
	ftservo/FTServo@^2.0.0
	adafruit/Adafruit BusIO@^1.17.4
monitor_speed = 115200
build_src_filter = +<*.h> +<main-Arm.cpp>
[env:Mecanum]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
	ftservo/FTServo@^2.0.0
	adafruit/Adafruit BusIO@^1.17.4
	br3ttb/PID
monitor_speed = 115200
build_src_filter = +<*.h> +<main-Mecanum.cpp>
[env:Solenoids]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
	ftservo/FTServo@^2.0.0
	adafruit/Adafruit BusIO@^1.17.4
monitor_speed = 115200
build_src_filter = +<*.h> +<main-Solenoids.cpp>
[env:Knob]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
	ftservo/FTServo@^2.0.0
	adafruit/Adafruit BusIO@^1.17.4
monitor_speed = 115200
build_src_filter = +<*.h> +<main-Knob.cpp>
